version: '3.8'

services:
  admin:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - db:${MYSQL_HOST}
    depends_on:
      - db
    ports:
      - "8080:80"
    networks:
      - nesjs-network
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      PMA_HOST: ${MYSQL_HOST}
      PMA_PORT: ${MYSQL_PORT}

  db:
    image: mysql:5.7
    container_name: ${MYSQL_HOST}
    volumes:
      - ./.docker/mysql/data:/var/lib/mysql
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}
    networks:
      - nesjs-network
    environment:
      MYSQL_TCP_PORT: ${MYSQL_PORT}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB_NAME}

  backend:
    container_name: backend_nest_api
    image: nestjs-api-dev:1.0.0
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    command: npm run start:debug
    ports:
      - ${WEBPORT}:${WEBPORT}
      - ${NODEDEBUGER}:${NODEDEBUGER}
    expose:
      - ${WEBPORT}
      - ${NODEDEBUGER}
    networks:
      - nesjs-network
    volumes:
      - .:/usr/src/app
    restart: unless-stopped
    env_file: ./.env

networks:
  nesjs-network:
